name: Build Docker Image
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build, lint and run tests
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: docker build . --file Dockerfile --tag ${{github.event.repository.name}}-$(date +"%m%d%Y")-${GITHUB_SHA::10}
